DB_URL  : "not required, using sql"
DB_NAME: "user_service_db"
HTTP_PORT : "8080"
GRPC_PORT : "50051"
USER_GRPC : "usergrpc:50051"
STORE_GRPC : "storegrpc:50052"
NOTIFICATION_GRPC : "notificationgrpc:50053"
IMAGE_GRPC : "imagegrpc:50055"
PRODUCT_GRPC : "productgrpc:50056"
MODE : "dev"
# USER_GRPC : "localhost:50051"
# STORE_GRPC : "localhost:50052"
# NOTIFICATION_GRPC : "localhost:50053"
# IMAGE_GRPC : "localhost:50055"
# PRODUCT_GRPC : "localhost:50056"
